### ISSUE TITLE
issue make

### ISSUE THREAD

**Issue by ecallejasbriones** [SimulationEverywhere/CDPP_ExtendedStates-codename-Santi#1]
Hi, I compiled this version but i have issues with command "cd++" 
![errormake01](https://user-images.githubusercontent.com/26755268/47627588-af7d0a80-db0f-11e8-9fcf-6b561a1f8eba.JPG)
![errormake02](https://user-images.githubusercontent.com/26755268/47627595-bf94ea00-db0f-11e8-82cf-2f6a3d7e1354.JPG)
![errormake03](https://user-images.githubusercontent.com/26755268/47627596-bf94ea00-db0f-11e8-9f25-35e81643c59b.JPG)
![errormake04](https://user-images.githubusercontent.com/26755268/47627597-bf94ea00-db0f-11e8-87d7-6742a7f9bc53.JPG)

**Comment by lukius** [comment]
@ecallejasbriones, it seems the compilation succeeded. The `cd++` executable should be located inside subdirectory `bin` (i.e., you should run `bin/cd++` instead of `cd++`). Please refer to the [README](../blob/master/README.md) file for further instructions on how to properly run the simulator.
