### ISSUE TITLE
Problems with Uppercase

### ISSUE THREAD

**Issue by ecallejasbriones** [SimulationEverywhere/CDPP_ExtendedStates-codename-Santi#2]
Hi again, I compiled my test and got an error. The solution was to change Uppercase to Lowercase of the TestEvacuacion03.val -> testevacuacion03.val

Error
![imagen](https://user-images.githubusercontent.com/26755268/47897674-72877f80-de51-11e8-9df7-51fab3ede31a.png)

With Solution
![imagen](https://user-images.githubusercontent.com/26755268/47897591-32c09800-de51-11e8-88d6-630b7e0c73b5.png)

my file TestEvacuacion03.ma
![imagen](https://user-images.githubusercontent.com/26755268/47897719-9ea30080-de51-11e8-9efd-f734c84da95b.png)

Best Regards
Exequiel

**Comment by lukius** [comment]
Thanks. I've just opened a new bug to address this issue. In the meantime, please use lowercase cell value filenames.
