### ISSUE TITLE
Multiples Logs

### ISSUE THREAD

**Issue by ecallejasbriones** [SimulationEverywhere/CDPP_ExtendedStates-codename-Santi#4]
UPDATED!edit 2:12am
*.log01 works well so far, but my directory is full withs others LOGs
===========================================

Good morning, I have problems with LOGS, multiple LOGS appear when the simulation ends

run simulation
![ejecucion a log](https://user-images.githubusercontent.com/26755268/48460404-9a5dd800-e7ad-11e8-8dc3-8168daadb140.PNG)

multiples LOGS
![archivos log 100](https://user-images.githubusercontent.com/26755268/48460418-ab0e4e00-e7ad-11e8-94b0-f24d18863ec8.PNG)

Which option do I have to choose?
![ejecucion help](https://user-images.githubusercontent.com/26755268/48460445-c5482c00-e7ad-11e8-9a56-79c04f2f6072.PNG)

I Have this LOG, always *.log01 more kb than rest LOGS
![log mas grande](https://user-images.githubusercontent.com/26755268/48460569-5b7c5200-e7ae-11e8-8579-a85356b6dff6.PNG)

Is *.log01 able for use in the projects?

best regards
Exequiel

**Comment by lukius** [comment]
It is completely normal to have several logs after running your simulations. You should have at least one log per model. For further details you can take a look at the main log file (i.e. the one that does not have an extension).
